// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ShortUrlRepository is an autogenerated mock type for the ShortUrlRepository type
type ShortUrlRepository struct {
	mock.Mock
}

// GetOriginalUrl provides a mock function with given fields: crx, shortUrl
func (_m *ShortUrlRepository) GetOriginalUrl(crx context.Context, shortUrl string) (string, error) {
	ret := _m.Called(crx, shortUrl)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(crx, shortUrl)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(crx, shortUrl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveOriginalUrl provides a mock function with given fields: ctx, originalUrl
func (_m *ShortUrlRepository) SaveOriginalUrl(ctx context.Context, originalUrl string) (string, error) {
	ret := _m.Called(ctx, originalUrl)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, originalUrl)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, originalUrl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
